### ISSUE TITLE
partial duplicate paths are not united

### ISSUE THREAD

**Issue by mcdon-ron** [tawman/git-unite#10]
The duplicate parent folder path i had was "Infrastructure/Data/Entity/" and "Infrastructure/data/Entity/". The files that were not united were in the folder "Infrastructure/data/Entity/Interceptors/". The "Interceptors/" folder existed only in the parent directory "Infrastructure/data/Entity/", and "Infrastructure/Data/Entity/" did not have an "Interceptors/" folder.

After doing a git mv for a single file from "Infrastructure/data/Entity/Interceptors/" to "Infrastructure/Data/Entity/Interceptors/", Git.Unite then identified and moved the remaining duplicates.

**Comment by tawman** [comment]
Thanks for reporting this and looks like I should be able to reproduce and fix.

**Comment by jdelrue** [comment]
We are having the same problem! Can you please look into it? Thanks so much for this awesome tool!

**Comment by tawman** [comment]
Let me know if  #11 fixed this issue and I can close, thanks.

**Comment by jellebleyaert** [comment]
This solved the problem. Thank you!

**Comment by tawman** [comment]
@jellebleyaert thanks for taking the time to verify the issue is resolved
