### ISSUE TITLE
Suggestion: Attach precompiled binaries to releases

### ISSUE THREAD

**Issue by sbrl** [tawman/git-unite#12]
Some of us are not able to compile your software as the running of powershell scripts is disabled on our systems, and we don't have the permissions necessary to change it. It would be really handy if you included precompiled binaries on Github's releases page,

**Comment by tawman** [comment]
The binaries with required libraries are 25 MB in size, which would add some untrusted bloat to the repo.

You can compile via the command line without using psake powershell scripts by calling msbuild from your .NET installation:
```
C:\git\git-unite> C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild /t:build /v:n /p:Configuration=DEBUG .\src\Git.Unite.sln
```

I explored creating a nuget package today but tools do not fit that model well. I can look at creating a [Chocolatey Package](https://chocolatey.org/) package when I get some free time.

Thanks.

**Comment by sbrl** [comment]
I totally understand the bloat issue, but binaries attached to [Github releases](https://help.github.com/articles/creating-releases/) are not actually committed to your repository, so they don't add bloat :-)

**Comment by sbrl** [comment]
Further reading: https://github.com/blog/1547-release-your-software

**Comment by tawman** [comment]
Thanks for the heads up.. did not see that feature of Github releases. I will look into it.

**Comment by Venryx** [comment]
This would be nice.

I tried running the powershell build script, but it said execution of scripts is restricted. I looked it up, and found out how to change that setting. I then ran the build script again, except now it's saying:
```
Build started 2017-04-07 01:37:23.
Project "C:\Root\Apps\@V\@Tools\git-unite\Main\src\Git.Unite.sln" on node 1 (clean target(s)).
C:\Root\Apps\@V\@Tools\git-unite\Main\src\Git.Unite.sln.metaproj : error MSB4126: The specified solution configuration
"DEBUG|HPD" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (
e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the
default solution configuration. [C:\Root\Apps\@V\@Tools\git-unite\Main\src\Git.Unite.sln]
Done Building Project "C:\Root\Apps\@V\@Tools\git-unite\Main\src\Git.Unite.sln" (clean target(s)) -- FAILED.
```

The same problem occurs when running the `msbuild` command above. In other words, I seemingly can't seem to use the program at the moment. : (

Thankfully I don't need it at the moment, as I was able to do the case fixes manually (since it's a small project). But for larger projects this would be nice. (an alternative is to change the name of the root directories to something else, commit, then change them back; but then I think it might break the file histories)

**Comment by Venryx** [comment]
Okay, I was able to get a little farther by adding ` /p:Platform="Any CPU"` to the msbuild script above:
```
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild /t:build /v:n /p:Configuration=DEBUG /p:Platform="Any CPU" .\src\Git.Unite.sln
```

However, I now get this error:
```
UniteRepository.cs(223,28): error CS1525: Invalid expression term '.' [C:\Root\Apps\@V\@Tools\git-unite\Main\src\LibGit
Unite\LibGitUnite.csproj]
UniteRepository.cs(223,29): error CS1003: Syntax error, ':' expected [C:\Root\Apps\@V\@Tools\git-unite\Main\src\LibGitU
nite\LibGitUnite.csproj]
Done Building Project "C:\Root\Apps\@V\@Tools\git-unite\Main\src\LibGitUnite\LibGitUnite.csproj" (default targets) -- F
AILED.

Done Building Project "C:\Root\Apps\@V\@Tools\git-unite\Main\src\Git.Unite.sln" (build target(s)) -- FAILED.


Build FAILED.

"C:\Root\Apps\@V\@Tools\git-unite\Main\src\Git.Unite.sln" (build target) (1) ->
"C:\Root\Apps\@V\@Tools\git-unite\Main\src\LibGitUnite\LibGitUnite.csproj" (default target) (2) ->
(CoreCompile target) ->
  UniteRepository.cs(223,28): error CS1525: Invalid expression term '.' [C:\Root\Apps\@V\@Tools\git-unite\Main\src\LibG
itUnite\LibGitUnite.csproj]
  UniteRepository.cs(223,29): error CS1003: Syntax error, ':' expected [C:\Root\Apps\@V\@Tools\git-unite\Main\src\LibGi
tUnite\LibGitUnite.csproj]

    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:03.48
```

**Comment by tawman** [comment]
Interesting and I created a [GitHub release for v2.1](https://github.com/tawman/git-unite/releases/tag/v2.1) with precompiled binaries attached.

I will look into a [Chocolatey Package](https://chocolatey.org/packages) when I find some rare free time.

**Comment by sbrl** [comment]
Ooooh, cool! Thanks a bunch, @tawman :D
