### ISSUE TITLE
Crash on running on git repository in Win 10

### ISSUE THREAD

**Issue by Kisty** [tawman/git-unite#8]
Hey! I tried this a few years ago and really helped! Tried using again, but I can't. Executed `Git.Unite.exe <git repo>`

Compiled OK with some warnings, Running on Windows 10 64-bit.

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at LibGit2Sharp.Core.NativeMethods.git_threads_init()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_repository_open(RepositorySafeHandle& repository, FilePath path)
   at LibGit2Sharp.Repository..ctor(String path, RepositoryOptions options)
   at LibGitUnite.UniteRepository..ctor(String path, OptionFlags options) in c:\Users\TimKist\Documents\GitHub\git-unite\src\LibGitUnite\UniteRepository.cs:line 32
   at LibGitUnite.GitUnite.Process(String gitPath, OptionFlags options) in c:\Users\TimKist\Documents\GitHub\git-unite\src\LibGitUnite\GitUnite.cs:line 44
   at Git.Unite.Program.Main(String[] args) in c:\Users\TimKist\Documents\GitHub\git-unite\src\Git.Unite\Program.cs:line 53
```

**Comment by tawman** [comment]
I just a fresh clone and build without issue on my Win 10 Pro x64 VM that never had the code before. I wonder if the nuget binaries did not clone clean for you.

[Win10 x64 Build Log](https://gist.github.com/tawman/70fc6edf46f492d44ebaa62e22bf46d5)

**Comment by tawman** [comment]
The internet suggests trying:
```
In the build definition:
Process => Build => Advanced => MSBuild argument 
add:
/p:GenerateBuildInfoConfigFile=false
```

**Comment by Kisty** [comment]
Ah, I'm building from `build.bat`, no VS installed at present...

**Comment by tawman** [comment]
you can update the build.bat to include the `/p:GenerateBuildInfoConfigFile=false`

**Comment by Kisty** [comment]
Didn't help :(. I also tried pointing to a newer version of LibGit2Sharp (0.23.1) but that didn't work. Not familiar with C# projects.

Here's my build log https://gist.github.com/Kisty/48ec8fe6363c8afb6a0ef0e92d37adec

**Comment by tawman** [comment]
Try this, I updated to the latest LibGit2Sharp libraries which simplified the interaction as the methods are exposed now and I do not need to dynamically invoke the methods.

You will find the latest update in the [develop ](https://github.com/tawman/git-unite/tree/develop) branch

**Comment by tawman** [comment]
build.bat not working whereas VS build does... give me a minute or two to fix that

**Comment by tawman** [comment]
Ok, try it now .. I replaced build.bat with build.cmd to support C# 6

**Comment by tawman** [comment]
Okay, performed a long overdue refactoring due to changes in the newer Lib2GitSharp libraries. I need to incorporate one out standing PR into the develop branch and will then merge.

Let me know how the develop branch build works for you.

**Comment by tawman** [comment]
This issue should be resolved with PR #9 when it is merged into master

**Comment by Kisty** [comment]
Thanks for that, man! Got it finally to install. Had to install Microsoft Build Tools 2015 for it to work as Build tools `14.0.0.0` wasn't available from nuget. Tried to find line which references `14.0.0.0` but couldn't find it.

Was getting following stacktrace. Shall I add instructions to the ReadMe for building from command line without VS installed?

```
Failed to load msbuild Toolset
  Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Error: 08/02/2017 11:23:11:
 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Exec: Error executing command  Tools\Nuget.exe restore -source "https://www.nuget.org/api/v2" $sln .
```

**Comment by tawman** [comment]
Good to know, I will remove the nuget restore from default.ps1 since I bundle the packages.

Thanks
